version: "3.3"
name: "electric_sql_prod"

services:
  electric:
    image: electricsql/electric
    pull_policy: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ELECTRIC_USAGE_REPORTING: false
      ELECTRIC_SECRET: ${ELECTRIC_SECRET}
      ELECTRIC_INSECURE: false
